### ISSUE TITLE
Can't compare persistent enum instances across reload

### ISSUE THREAD

**Issue by kevingriffin** [iknow/persistent_enum#4]
`==` works, but using as a hash key does not.

**Comment by kevingriffin** [comment]
`.eql?` ❌ 
`.equal?` ❌ 
`==` 🆗 
`===` 🆗

**Comment by thefloweringash** [comment]
This should be resolved by #14, see the [tests][] for this case.

[tests]: https://github.com/iknow/persistent_enum/pull/14/files#diff-430a9092f60c0f9c3a84a3f0affac0bbR388
